# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Poiku/Documents/ECE385/fnaf/fnaf.srcs/sources_1/bd/mb_fnaf/ip/mb_fnaf_microblaze_0_axi_intc_0/mb_fnaf_microblaze_0_axi_intc_0.xci
# IP: The module: 'mb_fnaf_microblaze_0_axi_intc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Poiku/Documents/ECE385/fnaf/fnaf.gen/sources_1/bd/mb_fnaf/ip/mb_fnaf_microblaze_0_axi_intc_0/mb_fnaf_microblaze_0_axi_intc_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_fnaf_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Poiku/Documents/ECE385/fnaf/fnaf.gen/sources_1/bd/mb_fnaf/ip/mb_fnaf_microblaze_0_axi_intc_0/mb_fnaf_microblaze_0_axi_intc_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_fnaf_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Poiku/Documents/ECE385/fnaf/fnaf.gen/sources_1/bd/mb_fnaf/ip/mb_fnaf_microblaze_0_axi_intc_0/mb_fnaf_microblaze_0_axi_intc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_fnaf_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/Poiku/Documents/ECE385/fnaf/fnaf.srcs/sources_1/bd/mb_fnaf/ip/mb_fnaf_microblaze_0_axi_intc_0/mb_fnaf_microblaze_0_axi_intc_0.xci
# IP: The module: 'mb_fnaf_microblaze_0_axi_intc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Poiku/Documents/ECE385/fnaf/fnaf.gen/sources_1/bd/mb_fnaf/ip/mb_fnaf_microblaze_0_axi_intc_0/mb_fnaf_microblaze_0_axi_intc_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_fnaf_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Poiku/Documents/ECE385/fnaf/fnaf.gen/sources_1/bd/mb_fnaf/ip/mb_fnaf_microblaze_0_axi_intc_0/mb_fnaf_microblaze_0_axi_intc_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_fnaf_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Poiku/Documents/ECE385/fnaf/fnaf.gen/sources_1/bd/mb_fnaf/ip/mb_fnaf_microblaze_0_axi_intc_0/mb_fnaf_microblaze_0_axi_intc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_fnaf_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
