# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/lab7_1_provided_fa24/mb_usb_hdmi_top.xdc

# Block Designs: bd/mb_fnaf/mb_fnaf.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_fnaf || ORIG_REF_NAME==mb_fnaf} -quiet] -quiet

# IP: bd/mb_fnaf/ip/mb_fnaf_microblaze_0_0/mb_fnaf_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_fnaf_microblaze_0_0 || ORIG_REF_NAME==mb_fnaf_microblaze_0_0} -quiet] -quiet

# IP: bd/mb_fnaf/ip/mb_fnaf_dlmb_v10_0/mb_fnaf_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_fnaf_dlmb_v10_0 || ORIG_REF_NAME==mb_fnaf_dlmb_v10_0} -quiet] -quiet

# IP: bd/mb_fnaf/ip/mb_fnaf_ilmb_v10_0/mb_fnaf_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_fnaf_ilmb_v10_0 || ORIG_REF_NAME==mb_fnaf_ilmb_v10_0} -quiet] -quiet

# IP: bd/mb_fnaf/ip/mb_fnaf_dlmb_bram_if_cntlr_0/mb_fnaf_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_fnaf_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_fnaf_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mb_fnaf/ip/mb_fnaf_ilmb_bram_if_cntlr_0/mb_fnaf_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_fnaf_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_fnaf_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mb_fnaf/ip/mb_fnaf_lmb_bram_0/mb_fnaf_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_fnaf_lmb_bram_0 || ORIG_REF_NAME==mb_fnaf_lmb_bram_0} -quiet] -quiet

# IP: bd/mb_fnaf/ip/mb_fnaf_xbar_0/mb_fnaf_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_fnaf_xbar_0 || ORIG_REF_NAME==mb_fnaf_xbar_0} -quiet] -quiet

# IP: bd/mb_fnaf/ip/mb_fnaf_microblaze_0_axi_periph_0/mb_fnaf_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_fnaf_microblaze_0_axi_periph_0 || ORIG_REF_NAME==mb_fnaf_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/mb_fnaf/ip/mb_fnaf_microblaze_0_axi_intc_0/mb_fnaf_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_fnaf_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mb_fnaf_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/mb_fnaf/ip/mb_fnaf_microblaze_0_xlconcat_0/mb_fnaf_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_fnaf_microblaze_0_xlconcat_0 || ORIG_REF_NAME==mb_fnaf_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/mb_fnaf/ip/mb_fnaf_mdm_1_0/mb_fnaf_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_fnaf_mdm_1_0 || ORIG_REF_NAME==mb_fnaf_mdm_1_0} -quiet] -quiet

# IP: bd/mb_fnaf/ip/mb_fnaf_clk_wiz_1_0/mb_fnaf_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_fnaf_clk_wiz_1_0 || ORIG_REF_NAME==mb_fnaf_clk_wiz_1_0} -quiet] -quiet

# IP: bd/mb_fnaf/ip/mb_fnaf_rst_clk_wiz_1_100M_0/mb_fnaf_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_fnaf_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==mb_fnaf_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/mb_fnaf/ip/mb_fnaf_axi_uartlite_0_0/mb_fnaf_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_fnaf_axi_uartlite_0_0 || ORIG_REF_NAME==mb_fnaf_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/mb_fnaf/ip/mb_fnaf_axi_gpio_0_0/mb_fnaf_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_fnaf_axi_gpio_0_0 || ORIG_REF_NAME==mb_fnaf_axi_gpio_0_0} -quiet] -quiet

# IP: bd/mb_fnaf/ip/mb_fnaf_axi_gpio_0_1/mb_fnaf_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_fnaf_axi_gpio_0_1 || ORIG_REF_NAME==mb_fnaf_axi_gpio_0_1} -quiet] -quiet

# IP: bd/mb_fnaf/ip/mb_fnaf_axi_gpio_0_2/mb_fnaf_axi_gpio_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_fnaf_axi_gpio_0_2 || ORIG_REF_NAME==mb_fnaf_axi_gpio_0_2} -quiet] -quiet

# IP: bd/mb_fnaf/ip/mb_fnaf_axi_timer_0_0/mb_fnaf_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_fnaf_axi_timer_0_0 || ORIG_REF_NAME==mb_fnaf_axi_timer_0_0} -quiet] -quiet

# IP: bd/mb_fnaf/ip/mb_fnaf_axi_quad_spi_0_0/mb_fnaf_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_fnaf_axi_quad_spi_0_0 || ORIG_REF_NAME==mb_fnaf_axi_quad_spi_0_0} -quiet] -quiet

# IP: ip/camani_2/camani.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==camani || ORIG_REF_NAME==camani} -quiet] -quiet

# IP: ip/office/office.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==office || ORIG_REF_NAME==office} -quiet] -quiet

# XDC: c:/Users/Poiku/Documents/ECE385/fnaf/fnaf.gen/sources_1/bd/mb_fnaf/mb_fnaf_ooc.xdc
