# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Poiku/Documents/ECE385/fnaf/fnaf.srcs/sources_1/ip/batt/batt.xci
# IP: The module: 'batt' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Poiku/Documents/ECE385/fnaf/fnaf.gen/sources_1/ip/batt/batt_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'batt'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/Poiku/Documents/ECE385/fnaf/fnaf.srcs/sources_1/ip/batt/batt.xci
# IP: The module: 'batt' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Poiku/Documents/ECE385/fnaf/fnaf.gen/sources_1/ip/batt/batt_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'batt'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
